# This triggers on all PRs to validate the change using Terraform Plan

name: Pull Request - Validate


on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:
    
concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  dev:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    name: "[DEV]"
    uses: faccomichele/utils-n-scripts/.github/workflows/terraform-run.yml@main
    with:
      environment: 'dev'
      region: 'eu-central-1'
      working-directory: './terraform'
      action: 'plan'
    secrets: inherit

  docker-build-dev:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    name: "[DEV-DOCKER-BUILD]"
    uses: faccomichele/utils-n-scripts/.github/workflows/ecr-docker-build.yml@main
    with:
      environment: 'dev'
      region: 'eu-central-1'
      working-directory: './docker'
      push-to-ecr: false
    secrets: inherit
  